version: '3.3'
services:
  pir-mqtt:
    build: .
    image: pir-mqtt-dockerized
    container_name: pir-mqtt-dockerized
    network_mode: host
    privileged: true
    restart: unless-stopped
    environment:
      GPIO_PIN: 7
      SCAN_INTERVAL: 100
      SENSOR_NAME: 'pir'
      MQTT_HOST: localhost
      MQTT_USER: ''
      MQTT_PASS: ''
